title: Desi Nabila Sari
email: desynabilasari98@gmail.com
description: > # this means to ignore newLines until "baseurl:"
 A personal blog by Desi Nabila Sari, a student at Politeknik Negeri Lhokseumawe.
 This blog is built using jekyll and hosted on GitHub Pages.
 The Content is primarily In Indonesian, but some posts may be in English
 
url: "https://desynabilasari.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag